version: "2"
services:
  api:
    build:
      context: ./emails
      dockerfile: Dockerfile
    networks:
      - mynet
    ports:
      - 9002:9002
    restart: always
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/share/nginx/html:cached
    networks:
      - mynet
    ports:
      - 3000:80
networks:
  mynet:
    driver: bridge
